version: '3'
services:
  wol:
    #image: "dabondi/go-rest-wol"
    container_name: go-rest-wol
    build: 
      context: .
    ports:
      - "7080:8080"

    # Warten auf die neue Version 
    volumes:
      - ./computer.csv:/app/computer.csv
#networks:
#  default:
#    external:
#      name: nat
